
export type InputsFormulaire = {
    email: string,
    chauffeurSignature: string,
    controllerSignature: string,
    ligne:string,
    numeroLigne: string,
    typeLigne: string,
    typeArret: string,
    zebra: string,
    pleineVoie: string,

    propreteExterieure: string;
    etatAffiche: string,
    presenceCadreAffichage:string,
    lieuControle: string,
    heurePrevue: string,
    heureReelle: string,
    date: Date,
    secteur: string,
    numeroParc: number,
    nom: string,
    prenom: string,
    affichageHoraire: string,
    respectItineraire?: boolean,
    affichageDestination?: boolean,
    affichageNumeroLigne?: boolean,
    pictoEnfant?: boolean,
    tarifAffiche?: boolean,
    depliantHoraire?: boolean,
    reglement?: boolean,
    tenue?: boolean,
    carosserie?: boolean,
    tableauBord?: boolean,
    sol?: boolean,
    temperature?: boolean,
    luminosite?: boolean,
    nbreVoyageur: number,
    nbreVoyageurIrregulier: number,
    observationArret: string,
    observationProprete:string,
    meteo: string,
    client: string,
    
}
