
export type InputsFormulaire = {
    email: string,
    chauffeurSignature: string,
    controllerSignature: string,
    ligne:string,
    numeroLigne: string,
    typeLigne: string,
    lieuControle: string,
    heurePrevue: string,
    heureReelle: string,
    date: Date,
    secteur: string,
    parc: number,
    nom: string,
    prenom: string,
    ficheHoraire?: boolean,
    respectItineraire?: boolean,
    affichageDestination?: boolean,
    affichageNumeroLigne?: boolean,
    pictoEnfant?: boolean,
    tarifAffiche?: boolean,
    depliantHoraire?: boolean,
    reglement?: boolean,
    tenue?: boolean,
    carosserie?: boolean,
    tableauBord?: boolean,
    sol?: boolean,
    temperature?: boolean,
    luminosite?: boolean,
    nbreVoyageur: number,
    nbreVoyageurIrregulier: number,
    observation: string,
    meteo: string,
    client: string,
    
}
